providers = ["node"]

[variables]
NPM_CONFIG_PRODUCTION = "false"

[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = [
  "npm ci --include=dev",
]

[phases.build]
cmds = [
  "npx prisma generate",
  "npx prisma migrate deploy",
  "npm run build",
  "npm prune --production"
]

[start]
cmd = "npm start"

[staticAssets]
"public" = "./" 